import Phaser from "phaser";
import { LEVEL, type CardKind } from "../game/level";
import { beginCooking, connectionReady, finishCooking, freshKitchen, placeCard, serve, SOCKET, PLATE, type KitchenState } from "../game/rules";
import { createKitchenLayout, type KitchenLayout, type Rect } from "../game/layout";
import bg from "../../assets/images/kitchen-background.webp";
import toaster from "../../assets/images/toaster.webp"; import board from "../../assets/images/cutting-board.webp"; import plate from "../../assets/images/plate.webp";
import bread from "../../assets/images/ingredient-0.webp"; import tomato from "../../assets/images/ingredient-1.webp"; import cheese from "../../assets/images/ingredient-2.webp";
import toast from "../../assets/images/state-0.webp"; import sliced from "../../assets/images/state-1.webp"; import finished from "../../assets/images/state-3.webp";
import waiting from "../../assets/images/tilly-waiting.webp"; import delighted from "../../assets/images/tilly-delighted.webp"; import heart from "../../assets/images/heart.webp"; import sparkle from "../../assets/images/sparkle.webp";
const assets: Record<string, string> = { bg, toaster, board, plate, bread, tomato, cheese, toast, sliced, finished, waiting, delighted, heart, sparkle };
const labels: Record<CardKind, string> = { bread: "BREAD", tomato: "TOMATO", cheese: "CHEESE", toaster: "TOASTER", board: "CUTTING BOARD" };
const equipment: Partial<Record<CardKind, string>> = { toaster: "toaster", board: "board" };

export class KitchenScene extends Phaser.Scene {
  private state: KitchenState = freshKitchen(LEVEL); private layout!: KitchenLayout; private selected: number | null = null;
  private dragging: { index: number; image: Phaser.GameObjects.Image } | null = null; private pendingDrag: { index: number; x: number; y: number } | null = null; private ghost: Phaser.GameObjects.Image | undefined; private ghostTween: Phaser.Tweens.Tween | undefined; private idleTimer: Phaser.Time.TimerEvent | undefined; private busy = false; private pendingResize = false; private token = 0; private audio: AudioContext | undefined;
  private message = "Place matching cards in the recipe map.";
  constructor() { super("KitchenScene"); }
  preload() { Object.entries(assets).forEach(([key, url]) => this.load.image(key, url)); }
  create() { this.scale.on(Phaser.Scale.Events.RESIZE, this.resize, this); this.events.once(Phaser.Scenes.Events.SHUTDOWN, this.shutdown, this); this.input.on("pointermove", this.onMove, this); this.input.on("pointerup", this.onUp, this); this.redraw(); }
  shutdown() { this.audio?.close(); this.audio = undefined; this.scale.off(Phaser.Scale.Events.RESIZE, this.resize, this); this.input.off("pointermove", this.onMove, this); this.input.off("pointerup", this.onUp, this); this.stopGhost(); this.tweens.killAll(); this.time.removeAllEvents(); }
  private resize() { if (this.busy) this.pendingResize = true; else this.redraw(); }
  private cue(frequency: number, duration = .08) { try { const AudioCtor = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioCtor) return; this.audio ??= new AudioCtor(); if (this.audio.state === "suspended") void this.audio.resume(); const oscillator = this.audio.createOscillator(); const gain = this.audio.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.035, this.audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, this.audio.currentTime + duration); oscillator.connect(gain).connect(this.audio.destination); oscillator.start(); oscillator.stop(this.audio.currentTime + duration); } catch { /* audio is optional */ } }
  private tx(x: number, y: number, text: string, size: number, color = "#493327", bold = false) { return this.add.text(x, y, text, { fontFamily: "Georgia", fontSize: `${size}px`, color, fontStyle: bold ? "bold" : "normal", align: "center", wordWrap: { width: 280 } }).setOrigin(.5); }
  private panel(r: Rect, color: number) { const g = this.add.graphics(); g.fillStyle(color, .9).fillRoundedRect(r.x, r.y, r.width, r.height, 20).lineStyle(4, 0x8d5938, .8).strokeRoundedRect(r.x, r.y, r.width, r.height, 20); }
  private redraw() { this.stopGhost(); this.children.removeAll(true); this.layout = createKitchenLayout(this.scale.width, this.scale.height); const w = this.scale.width, h = this.scale.height; const background = this.add.image(w / 2, h / 2, "bg"); const source = background.texture.getSourceImage() as HTMLImageElement; background.setScale(Math.max(w / source.width, h / source.height)); this.add.rectangle(w / 2, h / 2, w, h, 0xffe6b0, .1); const banner = { x: Math.max(8, w * .02), y: 8, width: Math.min(w * .68, 560), height: 62 }; this.panel(banner, 0x4a2d29); this.tx(banner.x + banner.width / 2, 27, "Tilly's Tomato Toast", Math.min(23, w * .052), "#fff3d4", true); this.tx(banner.x + banner.width / 2, 52, this.message, Math.min(13, w * .029), "#fff3d4"); this.drawCustomer(); this.drawBoard(); this.drawInventory(); if (this.state.phase !== "building") this.drawCookingOrServing(); else this.startGhostSoon(); this.updateStatus(); }
  private updateStatus() { const element = document.getElementById("kitchen-status"); if (element) element.textContent = this.message; }
  private drawCustomer() { const r = this.layout.customer; this.panel(r, 0xffe8bd89); const key = this.state.phase === "served" ? "delighted" : "waiting"; const backing = this.add.ellipse(r.x + r.width / 2, r.y + r.height * .48, r.width * .82, r.height * .78, 0xfff2d2); const portrait = this.add.image(backing.x, backing.y, key).setDisplaySize(r.width * .86, r.height * .86); const mask = this.make.graphics({ x: 0, y: 0 }); mask.fillEllipse(backing.x, backing.y, r.width * .78, r.height * .76); portrait.setMask(mask.createGeometryMask()); const orderX = r.x + r.width * .13, orderY = r.y + r.height * .18; this.add.circle(orderX, orderY, Math.min(34, r.width * .12), 0xfff8df).setStrokeStyle(3, 0x9b653f); this.add.image(orderX, orderY, "finished").setDisplaySize(Math.min(32, r.width * .11), Math.min(42, r.height * .2)); this.tx(r.x + r.width / 2, r.y + r.height - 12, this.state.phase === "served" ? "YUM!" : "Tilly", 18, "#573126", true); if (this.state.phase === "served") { this.add.image(r.x + r.width * .15, r.y + r.height * .18, "heart").setDisplaySize(42, 42); this.add.image(r.x + r.width * .85, r.y + r.height * .18, "sparkle").setDisplaySize(42, 42); } }
  private drawBoard() { const r = this.layout.board; this.panel(r, 0xfff4ddb0); this.tx(r.x + r.width / 2, r.y + 24, "RECIPE MAP", 17, "#75442e", true); const c = this.layout.sockets.map((s) => ({ x: s.x + s.width / 2, y: s.y + s.height / 2 })); const edges: [0 | 1 | 2 | 3, 1 | 3][] = [[SOCKET.bread, SOCKET.toaster], [SOCKET.tomato, SOCKET.board]]; const g = this.add.graphics(); edges.forEach(([a, b]) => { const lit = connectionReady(this.state, a, b); g.lineStyle(5, lit ? 0xf7c65d : 0x9e795a, lit ? 1 : .3); g.lineBetween(c[a]!.x, c[a]!.y, c[b]!.x, c[b]!.y); if (!lit) for (let t = .1; t < .9; t += .18) g.fillCircle(c[a]!.x + (c[b]!.x - c[a]!.x) * t, c[a]!.y + (c[b]!.y - c[a]!.y) * t, 3); }); const p = this.layout.plate; const output = { x: p.x + p.width / 2, y: p.y + p.height / 2 }; [SOCKET.toaster, SOCKET.board, SOCKET.cheese].forEach((from) => { const lit = connectionReady(this.state, from, PLATE); g.lineStyle(5, lit ? 0xf7c65d : 0x9e795a, lit ? 1 : .3); g.lineBetween(c[from]!.x, c[from]!.y, output.x, output.y); });
    LEVEL.sockets.forEach((socket, i) => { const s = this.layout.sockets[i]!; const filled = Boolean(this.state.placements[i]); const q = this.add.graphics(); q.fillStyle(filled ? 0xc78b56 : 0xfff8dc, .95).fillRoundedRect(s.x, s.y, s.width, s.height, 15).lineStyle(4, filled ? 0x8d5938 : 0xd4a04e, 1).strokeRoundedRect(s.x, s.y, s.width, s.height, 15); const kind = this.state.placements[i] ?? socket.accepts; const key = equipment[kind] ?? kind; this.add.image(s.x + s.width / 2, s.y + s.height / 2 - 7, key).setDisplaySize(s.width * .62, s.height * .62).setAlpha(filled ? 1 : .28); this.tx(s.x + s.width / 2, s.y + s.height - 9, socket.label, Math.min(12, s.width * .105), "#75442e", true); const z = this.add.zone(s.x - 12, s.y - 12, s.width + 24, s.height + 24).setOrigin(0).setInteractive(); z.on("pointerdown", () => this.place(i)); if (this.selected !== null && this.state.tray[this.selected] === socket.accepts) { const glow = this.add.rectangle(s.x + s.width / 2, s.y + s.height / 2, s.width + 12, s.height + 12).setStrokeStyle(5, 0xffe36e, .9); this.tweens.add({ targets: glow, alpha: .25, duration: 450, yoyo: true, repeat: -1 }); } }); this.add.image(p.x + p.width / 2, p.y + p.height / 2, "plate").setDisplaySize(p.width, p.height); this.tx(p.x + p.width / 2, p.y + p.height + 14, "OUTPUT", 13, "#fff3d4", true); }
  private drawInventory() { const r = this.layout.inventory; this.panel(r, 0x784b36); this.tx(r.x + r.width / 2, r.y + 17, "DRAG OR TAP A CARD", Math.min(16, r.width * .035), "#fff3d4", true); const gap = r.width / (this.state.tray.length + 1); const cardW = Math.min(100, Math.max(62, gap * .82)); this.state.tray.forEach((kind, index) => { const x = r.x + gap * (index + 1), y = r.y + r.height * .55, half = cardW / 2; const card = this.add.graphics(); card.fillStyle(this.selected === index ? 0xffe17c : 0x9d603e, .98).fillRoundedRect(x - half, y - 50, cardW, 100, 16).lineStyle(3, 0xffdfa0, 1).strokeRoundedRect(x - half, y - 50, cardW, 100, 16); this.add.image(x, y - 9, kind).setDisplaySize(Math.min(76, cardW - 10), 60); this.tx(x, y + 42, labels[kind], Math.min(11, cardW * .12), "#fff3d4", true).setWordWrapWidth(cardW - 6); const z = this.add.zone(x - half - 4, y - 54, cardW + 8, 108).setOrigin(0).setInteractive(); z.on("pointerdown", (pointer: Phaser.Input.Pointer) => this.beginDrag(index, pointer.x, pointer.y)); }); }
  private beginDrag(index: number, x: number, y: number) { if (this.busy) return; this.selected = index; this.pendingDrag = { index, x, y }; this.redraw(); }
  private onMove(pointer: Phaser.Input.Pointer) {
    if (this.pendingDrag && Phaser.Math.Distance.Between(pointer.x, pointer.y, this.pendingDrag.x, this.pendingDrag.y) > 8) {
      const kind = this.state.tray[this.pendingDrag.index]!;
      this.dragging = { index: this.pendingDrag.index, image: this.add.image(pointer.x, pointer.y, kind).setDisplaySize(92, 82).setDepth(20) };
      this.pendingDrag = null;
    }
    if (this.dragging) this.dragging.image.setPosition(pointer.x, pointer.y);
  }
  private onUp(pointer: Phaser.Input.Pointer) {
    this.pendingDrag = null;
    if (!this.dragging) return;
    const drag = this.dragging; this.dragging = null; drag.image.destroy();
    const socket = this.layout.sockets.findIndex((s) => pointer.x >= s.x - 25 && pointer.x <= s.x + s.width + 25 && pointer.y >= s.y - 25 && pointer.y <= s.y + s.height + 25);
    if (socket >= 0) this.place(socket); else { this.selected = null; this.message = "That card bounced back."; this.redraw(); }
  }
  private place(socket: number) { if (this.busy) return; if (this.selected === null) { this.message = "Choose a card — its shape glows."; this.redraw(); return; } const result = placeCard(this.state, LEVEL, this.selected, socket); if (result.result !== "placed") { this.cue(180); this.message = "Boing! That card needs a different shape."; this.flash(socket); this.selected = null; this.redraw(); return; } this.state = result.state; this.selected = null; this.cue(540); this.message = "Nice! The recipe branches from ingredients to the plate."; this.redraw(); if (this.state.tray.length === 0) this.runCooking(); }
  private flash(socket: number) { const s = this.layout.sockets[socket]; if (!s) return; const ring = this.add.rectangle(s.x + s.width / 2, s.y + s.height / 2, s.width + 14, s.height + 14).setStrokeStyle(6, 0xd9544d).setDepth(30); this.tweens.add({ targets: ring, alpha: 0, duration: 110, yoyo: true, repeat: 2, onComplete: () => ring.destroy() }); }
  private startGhostSoon() { if (this.state.tray.length === 0) return; this.idleTimer = this.time.delayedCall(1200, () => this.showGhost()); }
  private showGhost() { if (this.busy || this.state.phase !== "building" || !this.state.tray.length) return; const kind = this.state.tray[0]!; const socket = LEVEL.sockets.findIndex((s, i) => s.accepts === kind && !this.state.placements[i]); const target = this.layout.sockets[socket]; if (!target) return; const r = this.layout.inventory; const gap = r.width / (this.state.tray.length + 1); const ghost = this.add.image(r.x + gap, r.y + r.height * .55, kind).setDisplaySize(66, 58).setAlpha(.55).setDepth(15); this.ghost = ghost; this.ghostTween = this.tweens.add({ targets: ghost, x: target.x + target.width / 2, y: target.y + target.height / 2, duration: 850, delay: 100, yoyo: true, repeat: -1, ease: "Sine.inOut" }); }
  private stopGhost() { this.idleTimer?.remove(); this.ghostTween?.stop(); this.ghost?.destroy(); this.idleTimer = undefined; this.ghostTween = undefined; this.ghost = undefined; }
  private runCooking() { this.busy = true; this.state = beginCooking(this.state); this.message = "Cooking each branch of the recipe…"; this.redraw(); const run = ++this.token; const l = this.layout; const move = (key: string, from: Phaser.Math.Vector2, to: Phaser.Math.Vector2, done: () => void) => { const item = this.add.image(from.x, from.y, key).setDisplaySize(76, 68).setDepth(30); this.tweens.add({ targets: item, x: to.x, y: to.y, duration: 500, ease: "Sine.inOut", onComplete: () => { if (run !== this.token) { item.destroy(); return; } done(); } }); };
    const center = (i: number) => { const s = l.sockets[i]!; return new Phaser.Math.Vector2(s.x + s.width / 2, s.y + s.height / 2); }; const output = new Phaser.Math.Vector2(l.plate.x + l.plate.width / 2, l.plate.y + l.plate.height / 2);
    move("bread", center(0), center(1), () => {
      move("toast", center(1), output, () => {
        move("tomato", center(2), center(3), () => {
          move("sliced", center(3), output, () => {
            move("cheese", center(4), output, () => this.finishCooking(run));
          });
        });
      });
    });
  }
  private finishCooking(run: number) { if (run !== this.token) return; this.state = finishCooking(this.state); this.busy = false; this.pendingResize = false; this.cue(880, .16); this.message = "Your toast is ready! Tap the finished plate for Tilly."; this.redraw(); }
  private drawCookingOrServing() { if (this.state.phase === "serving") { const p = this.layout.plate; this.add.image(p.x + p.width / 2, p.y + p.height / 2, "finished").setDisplaySize(p.width * .8, p.height * .8); const z = this.add.zone(p.x - 20, p.y - 20, p.width + 40, p.height + 40).setOrigin(0).setInteractive(); z.on("pointerdown", () => this.servePlate()); } else this.tx(this.layout.board.x + this.layout.board.width / 2, this.layout.board.y + this.layout.board.height * .92, "Bread browns → tomato slices → cheese joins", 16, "#75442e", true); }
  private servePlate() { if (this.state.phase !== "serving") return; this.busy = true; const run = ++this.token; const p = this.layout.plate, c = this.layout.customer; const item = this.add.image(p.x + p.width / 2, p.y + p.height / 2, "finished").setDisplaySize(p.width * .8, p.height * .8).setDepth(30); this.tweens.add({ targets: item, x: c.x + c.width / 2, y: c.y + c.height / 2, scale: .35, duration: 700, ease: "Back.inOut", onComplete: () => { item.destroy(); if (run !== this.token) return; this.state = serve(this.state); this.busy = false; this.pendingResize = false; this.cue(1040, .18); this.message = "Tilly loved it!"; this.redraw(); this.celebrate(); } }); }
  private celebrate() { const r = this.layout.customer; ["heart", "sparkle", "heart"].forEach((key, i) => { const item = this.add.image(r.x + r.width * (.25 + i * .25), r.y + r.height * .2, key).setDisplaySize(36, 36); this.tweens.add({ targets: item, y: "-=35", alpha: 0, delay: i * 90, duration: 650, onComplete: () => item.destroy() }); }); this.addButton(); }
  private addButton() { const w = Math.min(280, this.scale.width * .35), x = this.scale.width / 2, y = this.scale.height * .9; const g = this.add.graphics(); g.fillStyle(0xc95c43, 1).fillRoundedRect(x - w / 2, y - 28, w, 56, 18); this.tx(x, y, "MAKE IT AGAIN", 21, "#fff3d4", true); this.add.zone(x - w / 2, y - 28, w, 56).setOrigin(0).setInteractive().on("pointerdown", () => { this.token++; this.state = freshKitchen(LEVEL); this.busy = false; this.selected = null; this.message = "Place matching cards in the recipe map."; this.redraw(); }); }
}
